apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laura-db

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: laura-db
  managed-by: kustomize
