apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laura-db-data
  namespace: laura-db
  labels:
    app: laura-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and specify storage class if needed
  # storageClassName: standard
